version: 2
updates:
  - package-ecosystem: npm
    directory: /remote
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      remote-dependencies:
        patterns: ["*"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
